name: santrihub
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.4.1
  flutter_screenutil: ^5.9.0
  dotted_border: ^2.1.0
  permission_handler: ^11.3.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  intl: ^0.18.1
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.5
  calendar_date_picker2: ^0.5.5
  infinite_scroll_pagination: ^4.0.0
  gap: ^3.0.1
  google_fonts: 6.1.0
  logger: ^2.1.0
  fpdart: ^1.1.0
  equatable: ^2.0.5
  flutter_quill: 9.2.14
  awesome_snackbar_content: ^0.1.3
  toastification: ^1.2.1
  image_picker_web: ^3.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/env/
  uses-material-design: true

